name: Oi nos diretorios

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  oioi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run script
        run: |
          exit 1
  testing:
    if: always()
    runs-on: ubuntu-latest
    needs: oioi
    steps:
      - name: check
        run: |
          echo "oioi result: ${{ needs.oioi.result }}"
          if [ "${{ needs.oioi.result }}" != "success" ]; then
            echo "oioi job failed"
            exit 1
          else
            echo "All required jobs passed"
          fi

