name: Oi nos diretorios

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  oioi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run script
        run: "scripts/basic.sh"
